### ISSUE TITLE
Is this still relevant?

### ISSUE THREAD

**Issue by vvvvalvalval** [martinklepsch/pseudo-names-error#1]
I just successfully deployed a tenzing-inspired Reagent application with `:pseudo-names` set to `true`.

Is there still an issue here?

**Comment by vvvvalvalval** [comment]
Sorry, I missed a few details in the description.

**Comment by martinklepsch** [comment]
@vvvvalvalval I just tested setting `:pseudo-names` to `false` and everything seems fine. Can you confirm that on your side?

**Comment by vvvvalvalval** [comment]
Sorry, I got it reversed, I meant "with `:pseudo-names` set to `false`".

Yup, everything is fine, sorry for the inconvenience.

**Comment by martinklepsch** [comment]
Ok. Great to hear. Thank you.
